// Generated by the web build; asset bindings omit Content-Length internally.
export const videoSizes=Object.freeze({
  "/assets/video/dulcinea-introduction.mp4": 19604676,
  "/assets/video/hospitality-people.mp4": 2366048,
  "/assets/video/medellin-after-dark.mp4": 2242720,
  "/assets/video/medellin-location.mp4": 6009522,
  "/assets/video/properties/aires.mp4": 1625531,
  "/assets/video/properties/fontanar.mp4": 1075890,
  "/assets/video/properties/montana.mp4": 1662892,
  "/assets/video/properties/monte-sereno.mp4": 1698801,
  "/assets/video/properties/san-lucas.mp4": 1669910,
  "/assets/video/stock/AdobeStock_1849343666.mp4": 8308715,
  "/assets/video/stock/AdobeStock_693150796.mp4": 10790034,
  "/assets/video/stock/AdobeStock_762119818.mp4": 1473225
});
