// Generated by the web build; asset bindings omit Content-Length internally.
export const videoSizes=Object.freeze({
  "/assets/video/properties/aires.mp4": 1625531,
  "/assets/video/properties/fontanar.mp4": 1075890,
  "/assets/video/properties/montana.mp4": 1662892,
  "/assets/video/properties/monte-sereno.mp4": 1698801,
  "/assets/video/properties/san-lucas.mp4": 1669910,
  "/assets/video/review/after-dark.mp4": 4463116,
  "/assets/video/review/city-life.mp4": 5897752,
  "/assets/video/review/lola-ber.mp4": 6738639,
  "/assets/video/review/oriente-landscape.mp4": 8028659,
  "/assets/video/stock/AdobeStock_1849343666.mp4": 8308715,
  "/assets/video/stock/AdobeStock_514654455.mp4": 2779832,
  "/assets/video/stock/AdobeStock_539938219.mp4": 1309712,
  "/assets/video/stock/AdobeStock_693150796.mp4": 10790034,
  "/assets/video/stock/AdobeStock_695926335.mp4": 16350907,
  "/assets/video/stock/AdobeStock_762119818.mp4": 1473225
});
