import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {assertDeploymentTarget} from './deployment-targets.mjs';
import {REVIEW_ORIGIN} from '../shared/social-metadata.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=JSON.parse((await readFile(path.join(root,'wrangler.preview.jsonc'),'utf8')).replace(/^\uFEFF/,''));
const branch=execFileSync('git',['-c',`safe.directory=${root.replaceAll('\\','/')}`,'branch','--show-current'],{cwd:root,encoding:'utf8'}).trim();
if(!['codex/radisson-independent','main'].includes(branch))throw Error('Review deployment branch check failed');
assertDeploymentTarget(config,'review');
const defaultConfig=JSON.parse((await readFile(path.join(root,'wrangler.jsonc'),'utf8')).replace(/^\uFEFF/,''));
assertDeploymentTarget(defaultConfig,'production');
const build=JSON.parse(await readFile(path.join(root,'dist/investor-build.json'),'utf8'));
assert.deepEqual(build,{version:1,mode:'review',origin:REVIEW_ORIGIN},'Run npm run build:review before deploying the review website');
const cli=process.env.WRANGLER_CLI;
if(!cli)throw Error('Set WRANGLER_CLI to the installed official Wrangler JS entrypoint');
execFileSync(process.execPath,[path.join(root,'scripts/verify-investor-build.mjs'),'--review'],{cwd:root,stdio:'inherit'});
execFileSync(process.execPath,[cli,'deploy','--config','wrangler.preview.jsonc'],{cwd:root,stdio:'inherit'});
