// Colombian Spanish localization for the presentation and its investor resources.
// Replacements are complete visible phrases so markup, data, figures and asset URLs stay intact.
import { financialTranslations, preserveFinancialIdentifiers } from './financial-spanish.mjs';

const translations = [
  ...financialTranslations,
  ['All amounts in US dollars.', 'Todos los montos en dólares estadounidenses.'],
  ['KIT Capital applies these criteria to properties selected for Dulcinea One.', 'KIT Capital aplica estos criterios a las propiedades seleccionadas para Dulcinea One.'],
  ['El Poblado &amp; El Oriente', 'El Poblado y El Oriente'],
  ['Apartments and penthouses in El Poblado; houses on land in El Oriente.', 'Apartamentos y penthouses en El Poblado; casas con terreno en El Oriente.'],
  ['Paid guest stays have a 28-night minimum and a target cap of $9,500 per 28 nights.', 'Las estadías pagadas tienen un mínimo de 28 noches y un tope objetivo de $9.500 por 28 noches.'],
  ['12% investor IRR', 'TIR del 12% para el inversionista'],
  ['Investor return target, after carry and gains tax.', 'Retorno objetivo para el inversionista, después de carry e impuestos sobre las ganancias.'],
  ['The minimum target is a 12% investor IRR after carry and gains tax. The current portfolio projects 14.6%; returns are not guaranteed.', 'El objetivo mínimo es una TIR del 12% para el inversionista después de carry e impuestos sobre las ganancias. El portafolio actual proyecta 14,6%; los retornos no están garantizados.'],
  ['Criteria marked as met reflect estimates of anticipated results for each property and the portfolio as a whole. They are subject to underwriting and due diligence, not confirmation of achieved results or a guarantee of future performance.', 'Los criterios señalados como cumplidos reflejan estimaciones de los resultados esperados de cada propiedad y del portafolio en su conjunto. Están sujetos a evaluación de inversión y debida diligencia; no confirman resultados ya alcanzados ni garantizan el desempeño futuro.'],
  ['Deal-level screening hurdle, after gains tax.', 'Umbral de selección por operación, después de impuestos sobre las ganancias.'],
  ['20% deal-level IRR', 'TIR del 20% por operación'],
  ['Return targets and assumptions', 'Objetivos de rentabilidad y supuestos'],
  ['The screening threshold is 20% deal-level IRR after gains tax. The fund’s projected 15.7% investor IRR is a separate portfolio projection, after tax and carry.', 'El umbral de selección es una TIR del 20% por operación después de impuestos sobre las ganancias. La TIR proyectada del 15,7% para el inversionista del fondo es una proyección independiente del portafolio, después de impuestos y carry.'],
  ['Selection targets. Membership documents govern.', 'Objetivos de selección. Prevalecen los documentos de suscripción.'],
  ['Disclaimer', 'Aviso legal'],
  ['Dulcinea One | Investor presentation', 'Dulcinea One | Presentación para inversionistas'],
  ['Dulcinea One — Financial statements', 'Dulcinea One — Estados financieros'],
  ['Dulcinea One — Acquisition criteria', 'Dulcinea One — Criterios de adquisición'],
  ['DULCINEA · INVESTOR PRESENTATION', 'DULCINEA · PRESENTACIÓN PARA INVERSIONISTAS'],
  ['Dulcinea One, first slide', 'Dulcinea One, primera diapositiva'],
  ['Skip to presentation', 'Ir a la presentación'],
  ['Skip to investor access', 'Ir al acceso para inversionistas'],
  ['Skip to financial statements', 'Ir a los estados financieros'],
  ['Skip to acquisition criteria', 'Ir a los criterios de adquisición'],
  ['Private investor presentation', 'Presentación privada para inversionistas'],
  ['Dulcinea is a real estate investment firm.', 'Dulcinea es una firma de inversión inmobiliaria.'],
  ['Medellín, Colombia.', 'Medellín, Colombia.'],
  ['Co-branded by Lola &amp; Ber Hospitality.', 'Con la marca compartida de Lola &amp; Ber Hospitality.'],
  ['Welcome to Dulcinea', 'Te damos la bienvenida a Dulcinea'],
  ['Investor access', 'Acceso para inversionistas'],
  ['Enter your details and the access password provided to you.', 'Ingresa tus datos y la contraseña de acceso que recibiste.'],
  ['Full name', 'Nombre completo'],
  ['Email address', 'Correo electrónico'],
  ['Access password', 'Contraseña de acceso'],
  ['Enter presentation', 'Ingresar a la presentación'],
  ['Your name and email are used for this sign-in only.', 'Tu nombre y correo se usan únicamente para este ingreso.'],
  ['Need an invitation?', '¿Necesitas una invitación?'],
  ['Request access', 'Solicitar acceso'],
  ['We couldn’t sign you in.', 'No pudimos iniciar tu sesión.'],
  ['Enter your name, a valid email address and the shared password.', 'Ingresa tu nombre, un correo válido y la contraseña compartida.'],
  ['That password is not correct. Please try again.', 'La contraseña no es correcta. Inténtalo de nuevo.'],
  ['Too many attempts. Please wait one minute and try again.', 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.'],
  ['Please submit a valid access form.', 'Envía un formulario de acceso válido.'],
  ['Please submit the form from this website.', 'Envía el formulario desde este sitio web.'],
  ['Access is temporarily unavailable.', 'El acceso no está disponible por el momento.'],
  ['This preview is not published.', 'Esta vista previa no está publicada.'],
  ['Dulcinea One | Investor presentation', 'Dulcinea One | Presentación para inversionistas'],
  ['Five selected homes across El Poblado and El Retiro, Medellín. Dulcinea’s first real estate fund, co-branded by Lola &amp; Ber Hospitality.', 'Cinco propiedades seleccionadas en El Poblado y El Retiro, Medellín. El primer fondo inmobiliario de Dulcinea, con la marca compartida de Lola &amp; Ber Hospitality.'],
  ['Panoramic view of Medellín’s green neighborhoods and mountain skyline', 'Vista panorámica de los barrios verdes de Medellín y las montañas'],
  ['Investor access · Dulcinea One', 'Acceso para inversionistas · Dulcinea One'],
  ['Skip to presentation', 'Ir a la presentación'],
  ['aria-label="Home"', 'aria-label="Inicio"'],
  ['>Home</a>', '>Inicio</a>'],
  ['aria-label="Financial statements"', 'aria-label="Estados financieros"'],
  ['>Financials</a>', '>Finanzas</a>'],
  ['aria-label="Acquisition criteria"', 'aria-label="Criterios de adquisición"'],
  ['>Criteria</a>', '>Criterios</a>'],
  ['>Explore</span>', '>Explorar</span>'],
  ['DULCINEA PRESENTS', 'DULCINEA PRESENTA'],
  ['Our first fund.', 'Nuestro primer fondo.'],
  ['Five homes in El Poblado and El Retiro.', 'Cinco propiedades en El Poblado y El Retiro.'],
  ['Take a look', 'Conózcalo'],
  ['First round · For qualified investors', 'Primera ronda · Para inversionistas calificados'],
  ['WHY MEDELLÍN', 'POR QUÉ MEDELLÍN'],
  ['Come for a week.', 'Ven por una semana.'],
  ['Stay for a season.', 'Quédate una temporada.'],
  ['Walkable El Poblado.', 'El Poblado, para recorrer a pie.'],
  ['Space and privacy in El Retiro.', 'Espacio y privacidad en El Retiro.'],
  ['foreign visitors in 2024', 'visitantes extranjeros en 2024'],
  ['Two places to call home', 'Dos lugares para sentirse en casa'],
  ['Apartments and penthouses. Established neighborhoods for relocating professionals and returning families.', 'Apartamentos y penthouses. Barrios consolidados para profesionales que se trasladan y familias que regresan.'],
  ['Houses on private grounds. More space, more privacy.', 'Casas en lotes privados. Más espacio, más privacidad.'],
  ['Visitor figure from the supplied presentation, citing SIT Medellín and Alcaldía de Medellín, 2024–25.', 'Cifra de visitantes tomada de la presentación suministrada, con fuentes SIT Medellín y Alcaldía de Medellín, 2024–25.'],
  ['AFTER DARK', 'AL CAER LA NOCHE'],
  ['Go out.', 'Sal a disfrutar.'],
  ['Come home.', 'Vuelve a casa.'],
  ['The city outside.', 'La ciudad, allá afuera.'],
  ['Good company inside.', 'La mejor compañía, en casa.'],
  ['LOLA &amp; BER HOSPITALITY · THE CO-BRAND', 'LOLA &amp; BER HOSPITALITY · LA MARCA COMPARTIDA'],
  ['Freedom to be', 'La libertad de ser'],
  ['wholly yourself.', 'tú mismo.'],
  ['A hospitality co-brand for sex-positive, open-minded adults.', 'Una marca compartida de hospitalidad para adultos de mente abierta, que viven su sexualidad con libertad.'],
  ['The Lola &amp; Ber idea', 'La idea de Lola &amp; Ber'],
  ['Born from retreats and events. Natural, warm, private spaces. Plants, stone and warm light.', 'Nació de retiros y eventos. Espacios naturales, cálidos y privados, con plantas, piedra y luz acogedora.'],
  ['Each home keeps its name within the Lola &amp; Ber Hospitality co-brand. Dulcinea operates the homes. No brand fee in the proposed model.', 'Cada propiedad conserva su nombre bajo la marca compartida Lola &amp; Ber Hospitality. Dulcinea opera las propiedades. El modelo propuesto no contempla un cobro por uso de marca.'],
  ['THE PRODUCT WE’RE BUILDING', 'EL PRODUCTO QUE ESTAMOS CREANDO'],
  ['The whole', 'Una propiedad'],
  ['home.', 'lista para vivir.'],
  ['Location. Design. Hospitality.', 'Ubicación. Diseño. Hospitalidad.'],
  ['Ready to live in when the work is done.', 'Lista para habitar cuando terminen las obras.'],
  ['What comes together', 'Todo lo que reunimos'],
  ['Established location', 'Ubicación consolidada'],
  ['Finished, not off-plan', 'Terminada, no sobre planos'],
  ['One design standard', 'Un estándar de diseño'],
  ['Rental management', 'Administración de alquileres'],
  ['Available now', 'Disponible de inmediato'],
  ['A branded option', 'Una opción con marca'],
  ['SOURCE DECK’S MARKET ASSESSMENT', 'EVALUACIÓN DE MERCADO DE LA PRESENTACIÓN'],
  ['New-build developers', 'Desarrolladores de obra nueva'],
  ['Resale agencies', 'Agencias de reventa'],
  ['Owner-sellers', 'Propietarios vendedores'],
  ['Individual flippers', 'Inversionistas de remodelación y reventa'],
  ['Product criteria and qualitative positioning from the supplied deck. Availability is the intended finished product, not the current status of all five homes.', 'Criterios de producto y posicionamiento cualitativo tomados de la presentación suministrada. “Disponible” describe el producto terminado que se busca, no el estado actual de las cinco propiedades.'],
  ['HOW IT WORKS', 'CÓMO FUNCIONA'],
  ['Buy. Improve.', 'Comprar. Mejorar.'],
  ['Rent. Sell.', 'Alquilar. Vender.'],
  ['Dulcinea is a real estate investment firm with a unique platform focused on Medellín, Colombia.', 'Dulcinea es una firma de inversión inmobiliaria con una plataforma única enfocada en Medellín, Colombia.'],
  ['Dulcinea One is our first fund.', 'Dulcinea One es nuestro primer fondo.'],
  ['The company and the investment', 'La firma y la inversión'],
  ['Dulcinea’s investment fund will own and fund the homes; Dulcinea manages acquisition, renovation, operation and sale.', 'El fondo de inversión Dulcinea One será propietario de las viviendas y financiará su adquisición; Dulcinea estará a cargo de comprarlas, remodelarlas, operarlas y venderlas.'],
  ['The real estate investment firm behind the platform. Dulcinea manages acquisition, renovation, hospitality and sale.', 'La firma de inversión inmobiliaria detrás de la plataforma. Dulcinea administra la adquisición, remodelación, hospitalidad y venta.'],
  ['The co-brand of Dulcinea One and its homes. Each home keeps its own name.', 'La marca compartida de Dulcinea One y sus propiedades. Cada propiedad conserva su propio nombre.'],
  ['THE ACQUISITION DISCIPLINE', 'DISCIPLINA DE ADQUISICIÓN'],
  ['The right home.', 'La propiedad adecuada.'],
  ['The right price.', 'Al precio correcto.'],
  ['Homes we’d want to live in.', 'Propiedades donde quisiéramos vivir.'],
  ['A price that leaves room to improve.', 'Un precio que permita crear valor.'],
  ['Location. Diligence. A clear plan to sell.', 'Ubicación. Debida diligencia. Un plan claro de venta.'],
  ['Acquisition criteria', 'Criterios de adquisición'],
  ['The ten acquisition tests', 'Diez criterios de adquisición'],
  ['El Poblado and El Retiro.', 'El Poblado y El Retiro.'],
  ['Homes we’d want to live in.', 'Propiedades donde quisiéramos vivir.'],
  ['Apartments, penthouses and houses.', 'Apartamentos, penthouses y casas.'],
  ['All-in cost below improved comparable value.', 'Costo total inferior al valor de propiedades comparables remodeladas.'],
  ['A defined renovation and furnishing plan.', 'Un plan definido de remodelación y dotación.'],
  ['Technical, legal and title review.', 'Revisión técnica, jurídica y de títulos.'],
  ['Furnished homes, with rental management.', 'Propiedades amobladas y con administración de alquileres.'],
  ['A clear timetable and plan to sell.', 'Un cronograma y plan de venta claros.'],
  ['A disciplined budget for each home.', 'Un presupuesto disciplinado para cada propiedad.'],
  ['An underwritten return that clears our hurdle.', 'Un rendimiento proyectado que supere nuestro mínimo.'],
  ['KIT Capital applies acquisition criteria to select properties. Targets guide selection; each property requires its own underwriting.', 'KIT Capital aplica criterios de adquisición para seleccionar propiedades. Los objetivos orientan la selección; cada propiedad requiere su propio análisis financiero.'],
  ['THE INVESTMENT', 'LA INVERSIÓN'],
  ['Buy well.', 'Comprar bien.'],
  ['Build value.', 'Crear valor.'],
  ['projected investor IRR', 'TIR proyectada para el inversionista'],
  ['projected capital multiple', 'múltiplo proyectado sobre el capital'],
  ['modeled liquidation', 'liquidación proyectada en el modelo'],
  ['Projected returns on called capital, after modeled tax and carry. Not guaranteed.', 'Rendimientos proyectados sobre el capital aportado, después de impuestos y participación de éxito modelados. No están garantizados.'],
  ['THE HOMES', 'LAS PROPIEDADES'],
  ['60+ homes walked.', 'Más de 60 propiedades visitadas.'],
  ['Five selected.', 'Cinco seleccionadas.'],
  ['Two signed for closing. Three in negotiation.', 'Dos firmadas, pendientes de cierre. Tres en negociación.'],
  ['Previous homes', 'Propiedades anteriores'],
  ['Next homes', 'Propiedades siguientes'],
  ['El Poblado · Apartment', 'El Poblado · Apartamento'],
  ['El Poblado · Penthouse', 'El Poblado · Penthouse'],
  ['El Retiro · House', 'El Retiro · Casa'],
  ['AI lifestyle visualizations. Source-reported acquisition status. Open a home to see more.', 'Visualizaciones de estilo de vida generadas con IA. Estado de adquisición reportado por la fuente. Abre una propiedad para conocer más.'],
  ['Animated AI lifestyle illustration', 'Ilustración de estilo de vida animada con IA'],
  ['PROPERTY 1 / 5', 'PROPIEDAD 1 / 5'],
  ['PROPERTY 2 / 5', 'PROPIEDAD 2 / 5'],
  ['PROPERTY 3 / 5', 'PROPIEDAD 3 / 5'],
  ['PROPERTY 4 / 5', 'PROPIEDAD 4 / 5'],
  ['PROPERTY 5 / 5', 'PROPIEDAD 5 / 5'],
  ['El Poblado, Medellín', 'El Poblado, Medellín'],
  ['El Retiro, Antioquia', 'El Retiro, Antioquia'],
  ['Apartment · 325 m² (3,498 sq ft)', 'Apartamento · 325 m² (3.498 pies²)'],
  ['Penthouse · 489 m² (5,264 sq ft)', 'Penthouse · 489 m² (5.264 pies²)'],
  ['Penthouse · 389 m² (4,187 sq ft)', 'Penthouse · 389 m² (4.187 pies²)'],
  ['House · 420 m² on a 2,940 m² lot', 'Casa · 420 m² en un lote de 2.940 m²'],
  ['House · 591 m² (6,361 sq ft)', 'Casa · 591 m² (6.361 pies²)'],
  ['An apartment in an established El Poblado neighborhood.', 'Un apartamento en un barrio consolidado de El Poblado.'],
  ['A penthouse with room to bring everyone together.', 'Un penthouse amplio, pensado para compartir.'],
  ['A penthouse built around generous living spaces.', 'Un penthouse con amplios espacios para disfrutar.'],
  ['A house on private grounds in El Retiro.', 'Una casa en un lote privado en El Retiro.'],
  ['A home among the trees in El Retiro.', 'Una propiedad rodeada de árboles en El Retiro.'],
  ['Negotiated; compraventa drafted', 'En negociación; promesa de compraventa en preparación'],
  ['Signed; closing September 2026', 'Firmada; cierre previsto para 4T26'],
  ['Negotiated; finalizing modifications', 'En negociación; se ultiman modificaciones'],
  ['Negotiated; works being budgeted', 'En negociación; presupuesto de obras en preparación'],
  ['View illustration', 'Ver ilustración'],
  ['Original imagery', 'Imágenes originales'],
  ['Floorplans', 'Planos arquitectónicos'],
  ['All five homes', 'Ver las cinco propiedades'],
  ['The Dulcinea', 'El equipo'],
  ['team.', 'de Dulcinea.'],
  ['Managing Director', 'Director general'],
  ['Investment Partner', 'Socio de inversión'],
  ['Business Development', 'Desarrollo de negocios'],
  ['Team backgrounds', 'Experiencia del equipo'],
  ['Founder of KIT Capital. Two NASDAQ/TSE listings and several private exits. Ex-Goldman Sachs. Harvard BA and MA.', 'Fundador de KIT Capital. Dos listados en NASDAQ/TSE y varias ventas de compañías privadas. Ex Goldman Sachs. Títulos de pregrado y maestría de Harvard.'],
  ['30 years operating and restructuring businesses, including HP, Dell and RealNetworks. Led M&A on $1.5B of transactions.', 'Treinta años de experiencia operando y reestructurando empresas, incluidas HP, Dell y RealNetworks. Lideró fusiones y adquisiciones en transacciones por USD 1.500 millones.'],
  ['Luxury tourism and hospitality experience, including hotels and high-profile events, with a focus on the guest experience.', 'Experiencia en turismo de lujo y hospitalidad, incluidos hoteles y eventos de alto perfil, con énfasis en la experiencia del huésped.'],
  ['ON THE GROUND', 'EN TERRENO'],
  ['Local people.', 'Equipo local.'],
  ['Clear responsibilities.', 'Responsabilidades claras.'],
  ['Architecture', 'Arquitectura'],
  ['Design and works', 'Diseño y obra'],
  ['Interventoría', 'Interventoría'],
  ['Works oversight', 'Supervisión de obra'],
  ['Legal', 'Asesoría legal'],
  ['Title and closing', 'Estudio de títulos y cierre'],
  ['Accounting and tax', 'Contabilidad e impuestos'],
  ['Books and gains tax', 'Contabilidad e impuesto a las ganancias'],
  ['Open the supplied Fontanar architectural plans', 'Abrir los planos arquitectónicos suministrados de Fontanar'],
  ['Fontanar · Supplied architectural plan', 'Fontanar · Plano arquitectónico suministrado'],
  ['DULCINEA ONE · THE OFFER', 'DULCINEA ONE · LA OFERTA'],
  ['Join the', 'Súmate al'],
  ['first fund.', 'primer fondo.'],
  ['Membership units in a five-home portfolio. No debt.', 'Participaciones en un portafolio de cinco propiedades. Sin deuda.'],
  ['open to new investors', 'disponibles para nuevos inversionistas'],
  ['total fund raise', 'meta total de capital del fondo'],
  ['already committed', 'ya comprometidos'],
  ['What you invest in', 'En qué inviertes'],
  ['Dulcinea One fund units', 'Participaciones del fondo Dulcinea One'],
  ['Membership in a Delaware LLC investment fund, not ownership of an individual home.', 'Participación en un fondo de inversión LLC constituido en Delaware; no implica ser propietario de una vivienda individual.'],
  ['$10,000 Membership Units', 'Participaciones desde USD 10.000'],
  ['Capital called as acquisitions and operations require.', 'El capital se solicita según las necesidades de adquisición y operación.'],
  ['Only after all contributed capital is returned. Four-year modeled liquidation.', 'Solo después de devolver todo el capital aportado. Liquidación proyectada a cuatro años.'],
  ['Source-reported commitments. Membership documents govern.', 'Compromisos reportados por la fuente. Prevalecen los documentos de suscripción.'],
  ['RIGHTS WITH THE UNITS', 'DERECHOS DE LAS PARTICIPACIONES'],
  ['More than', 'Más que'],
  ['the homes.', 'las propiedades.'],
  ['Lola &amp; Ber equity', 'participación en Lola &amp; Ber'],
  ['At full fund subscription.', 'Al completar la suscripción del fondo.'],
  ['Future rounds', 'Rondas futuras'],
  ['Optional participation.', 'Participación opcional.'],
  ['Managing Partner', 'Socio administrador'],
  ['Participation in platform economics.', 'Participación en los resultados económicos de la plataforma.'],
  ['Additional rights. Outside the projected returns.', 'Derechos adicionales. No están incluidos en los rendimientos proyectados.'],
  ['Rights and conditions', 'Derechos y condiciones'],
  ['Brand equity is up to 3% at full subscription. Future-round participation is optional. Managing Partner priority, allocation and vesting follow the Membership documents.', 'La participación en la marca puede llegar hasta el 3% al completar la suscripción. La participación en rondas futuras es opcional. La prioridad, asignación y consolidación de derechos del Socio Administrador se rigen por los documentos de suscripción.'],
  ['Membership documents govern.', 'Prevalecen los documentos de suscripción.'],
  ['DULCINEA ONE · NEXT STEP', 'DULCINEA ONE · SIGUIENTE PASO'],
  ['Discuss your', 'Hablemos de tu'],
  ['investment.', 'inversión.'],
  ['Message Dov on WhatsApp', 'Escríbele a Dov por WhatsApp'],
  ['For qualified investors. Membership documents govern.', 'Para inversionistas calificados. Prevalecen los documentos de suscripción.'],
  ['Back to top', 'Volver al inicio'],
  ['Enter fullscreen', 'Activar pantalla completa'],
  ['Previous chapter', 'Capítulo anterior'],
  ['Next chapter', 'Capítulo siguiente'],
  ['Close slide menu', 'Cerrar menú de diapositivas'],
  ['Close', 'Cerrar'],
  ['THE STORY', 'LA HISTORIA'],
  ['Explore<br/><em>Dulcinea One</em>', 'Conoce<br/><em>Dulcinea One</em>'],
  ['Scroll to explore.', 'Desplázate para explorar.'],
  ['Use the arrows to jump between chapters.', 'Usa las flechas para ir de un capítulo a otro.'],
  ['Choose a chapter', 'Elegir un capítulo'],
  ['Why Medellín', 'Por qué Medellín'],
  ['After dark', 'Al caer la noche'],
  ['The whole home', 'La propiedad completa'],
  ['How it works', 'Cómo funciona'],
  ['Buying well', 'Comprar bien'],
  ['The investment', 'La inversión'],
  ['The five homes', 'Las cinco propiedades'],
  ['The team', 'El equipo'],
  ['On the ground', 'En terreno'],
  ['The first round', 'La primera ronda'],
  ['Additional rights', 'Derechos adicionales'],
  ['Talk to Dov', 'Habla con Dov'],
  ['Investor resources', 'Recursos para inversionistas'],
  ['INVESTOR RESOURCES', 'RECURSOS PARA INVERSIONISTAS'],
  ['Income statement', 'Estado de resultados'],
  ['Balance sheet', 'Balance general'],
  ['Sources &amp; investment notes', 'Fuentes y notas de inversión'],
  ['The opening sequence combines aerial films, a moving city photograph and animated property visualizations. The five property lifestyle illustrations were generated with AI from the supplied property images. Their nine-second videos add slow camera movement; the people are not filmed footage. People and furnishing arrangements are illustrative. Original imagery and the four confirmed floorplan sets remain available from the property pages. Plans preserve source area labels; these can differ from the presentation.', 'La secuencia inicial combina videos aéreos, una fotografía de la ciudad con movimiento y visualizaciones animadas de las propiedades. Las cinco ilustraciones de estilo de vida se generaron con IA a partir de las imágenes suministradas. Sus videos de nueve segundos incorporan movimientos lentos de cámara; las personas no son imágenes filmadas. Las personas y la distribución del mobiliario son ilustrativas. Las imágenes originales y los cuatro juegos de planos confirmados están disponibles en las páginas de cada propiedad. Los planos conservan las áreas indicadas en la fuente, que pueden diferir de las cifras de la presentación.'],
  ['Dulcinea is a real estate investment firm with a unique platform focused on Medellín, Colombia, presenting its Dulcinea One fund, co-branded by Lola &amp; Ber Hospitality. Content is based on Dulcinea – Investor Presentation 027; figures were checked against Dulcinea Model 07. Projected returns are on called capital, after modeled tax and carry, and are not guaranteed. Membership documents govern.', 'Dulcinea es una firma de inversión inmobiliaria con una plataforma única enfocada en Medellín, Colombia, y presenta su fondo Dulcinea One con la marca compartida Lola &amp; Ber Hospitality. El contenido se basa en Dulcinea – Investor Presentation 027; las cifras se contrastaron con Dulcinea Model 07. Los rendimientos proyectados se calculan sobre el capital aportado, después de impuestos y participación de éxito modelados, y no están garantizados. Prevalecen los documentos de suscripción.'],
  ['Acquisition statuses follow the property pages: two signed for September 2026 closing and three in negotiation. A signed property is not presented as a completed closing. Photos and property imagery come from the supplied presentation; City and hospitality scenes illustrate the setting and experience. Logo artwork and the supplied Pantone palette are preserved.', 'Los estados de adquisición corresponden a las páginas de las propiedades: dos están firmadas y pendientes de cierre en 4T26; tres siguen en negociación. Una propiedad firmada no se presenta como una compra ya cerrada. Las fotografías y las imágenes de las propiedades provienen de la presentación suministrada; las escenas de la ciudad y de hospitalidad ilustran el entorno y la experiencia. Se conservan los logos y la paleta Pantone suministrada.'],
  ['Visual inspiration:', 'Inspiración visual:'],
  ['All three team portraits use the newly supplied photographs.', 'Los tres retratos del equipo usan las fotografías nuevas suministradas.'],
  ['The after-dark sequence combines the supplied night-road and neon films with camera moves across the evening and nightlife photographs. People in the photographs remain still.', 'La secuencia nocturna combina los videos suministrados de calles de noche y luces de neón con movimientos de cámara sobre las fotografías de la tarde y la vida nocturna. Las personas en las fotografías permanecen quietas.'],
  ['original imagery supplied in the investor presentation', 'imágenes originales suministradas en la presentación para inversionistas'],
  ['Original supplied property imagery', 'Imágenes originales de la propiedad'],
  ['complete supplied drawing', 'plano completo suministrado'],
  ['Source page', 'Página de la fuente'],
  ['of 9. Area labels are as supplied.', 'de 9. Las etiquetas de área son las suministradas.'],
  ['Property imagery', 'Imágenes de la propiedad'],
  ['Close property viewer', 'Cerrar visor de la propiedad'],
  ['Previous image', 'Imagen anterior'],
  ['Next image', 'Imagen siguiente'],
  ['Zoom in', 'Ampliar'],
  ['Download supplied plans', 'Descargar los planos suministrados'],
  ['Download image', 'Descargar imagen'],
  ['AI lifestyle visualization based on supplied property imagery.', 'Visualización de estilo de vida generada con IA a partir de imágenes suministradas de la propiedad.'],
  ['AI-generated lifestyle visualization based on supplied property imagery.', 'Visualización de estilo de vida generada con IA a partir de imágenes suministradas de la propiedad.'],
  ['lifestyle visualization with fictional adults', 'visualización de estilo de vida con adultos ficticios'],
  ['City aerials and animated property lifestyle scenes', 'Tomas aéreas de la ciudad y escenas animadas de estilo de vida en las propiedades'],
  ['City aerials and a walk along a tree-lined neighborhood street', 'Tomas aéreas de la ciudad y recorrido por una calle arbolada del barrio'],
  ['DJ and crowd enjoying a night out', 'DJ y público disfrutando la noche'],
  ['Chefs preparing food and countryside lifestyle', 'Chefs preparando platos y vida en el campo'],
  ['An agent and an adult couple viewing an apartment', 'Un asesor inmobiliario y una pareja adulta recorren un apartamento'],
  ['Fictional adults enjoying coffee in a San Lucas lifestyle visualization', 'Adultos ficticios tomando café en una visualización de estilo de vida de San Lucas'],
  ['Chapter ', 'Capítulo '],
  [' of ', ' de '],
  ['Zoom out', 'Reducir'],
  ['Fit to screen', 'Ajustar a la pantalla'],
  ['Slide menu is unavailable in this browser. Use the navigation arrows.', 'El menú de diapositivas no está disponible en este navegador. Usa las flechas de navegación.'],
  ['Exit fullscreen', 'Salir de pantalla completa'],
  ['Fullscreen is unavailable in this browser.', 'La pantalla completa no está disponible en este navegador.'],
  ['Fullscreen could not be opened. The presentation remains available in this window.', 'No se pudo activar la pantalla completa. La presentación sigue disponible en esta ventana.'],
  ['Financial statements', 'Estados financieros'],
  ['← Back to presentation', '← Volver a la presentación'],
  ['Dulcinea One · Model 07', 'Dulcinea One · Modelo 07'],
  ['Projected fund results in USD, October 2026–September 2030.', 'Resultados proyectados del fondo en USD, octubre de 2026 a septiembre de 2030.'],
  ['These are model projections, not audited actuals or guaranteed returns.', 'Son proyecciones del modelo, no resultados auditados ni rendimientos garantizados.'],
  ['Income statement', 'Estado de resultados'],
  ['Balance sheet', 'Balance general'],
  ['Projected income statement', 'Estado de resultados proyectado'],
  ['Fund income before carried-interest distributions. Each model year runs from October through September.', 'Ingresos del fondo antes de distribuir la participación de éxito. Cada año del modelo va de octubre a septiembre.'],
  ['USD rounded to whole dollars, except percentages. Parentheses indicate deductions or losses.', 'USD redondeados al dólar, excepto los porcentajes. Los paréntesis indican deducciones o pérdidas.'],
  ['Model year', 'Año del modelo'],
  ['Year 1', 'Año 1'], ['Year 2', 'Año 2'], ['Year 3', 'Año 3'], ['Year 4', 'Año 4'],
  ['Oct ', 'Oct '], ['Sep ', 'Sep '],
  ['Total', 'Total'],
  ['Years 1–4 · derived', 'Años 1–4 · calculado'],
  ['Rental income', 'Ingresos por alquiler'],
  ['Property sales (gross)', 'Venta de propiedades (bruta)'],
  ['Total revenue', 'Ingresos totales'],
  ['Variable costs', 'Costos variables'],
  ['Contribution margin', 'Margen de contribución'],
  ['Contribution margin %', 'Margen de contribución %'],
  ['Fixed property costs', 'Costos fijos de las propiedades'],
  ['Fund-level fixed costs', 'Costos fijos del fondo'],
  ['Modeled taxes', 'Impuestos modelados'],
  ['Net income before carry', 'Utilidad neta antes de participación de éxito'],
  ['Scroll horizontally to view every year on smaller screens.', 'Desplázate horizontalmente para ver todos los años en pantallas pequeñas.'],
  ['Contribution margin is revenue less property cost basis, selling costs and rent-linked fees and taxes. Fixed property costs include predial, insurance, HOA, utilities and maintenance. Fund-level costs include asset management, administration and transaction tax.', 'El margen de contribución corresponde a los ingresos menos el costo base de las propiedades, los gastos de venta y las tarifas e impuestos asociados al alquiler. Los costos fijos de las propiedades incluyen impuesto predial, seguros, administración, servicios públicos y mantenimiento. Los costos del fondo incluyen administración de activos, administración general e impuesto a las transacciones.'],
  ['The model assumes 15% tax on property gains and zero rental income tax after cumulative losses. Totals use unrounded annual values; sums of displayed numbers can differ by $1. Net income is before carry and is not an investor distribution.', 'El modelo supone un impuesto del 15% sobre las ganancias de las propiedades y ningún impuesto sobre los ingresos de alquiler después de pérdidas acumuladas. Los totales usan valores anuales sin redondear; la suma de las cifras mostradas puede diferir en USD 1. La utilidad neta es antes de la participación de éxito y no corresponde a una distribución al inversionista.'],
  ['Source and calculation notes', 'Fuente y notas de cálculo'],
  ['rows ', 'filas '],
  ['Model periods:', 'Periodos del modelo:'],
  ['Property-gains tax assumption:', 'Supuesto de impuesto sobre ganancias de propiedades:'],
  ['rental tax calculation:', 'cálculo del impuesto sobre alquileres:'],
  ['The Total column sums saved, unrounded annual values; its contribution margin percentage divides total contribution by total revenue. Saved formula results were inspected without recalculating the workbook. The model has no income from Year 5 onward.', 'La columna Total suma los valores anuales guardados sin redondear; el porcentaje del margen de contribución divide el margen total entre los ingresos totales. Se revisaron los resultados guardados de las fórmulas sin recalcular el archivo. El modelo no contempla ingresos a partir del año 5.'],
  ['Projected balance sheet', 'Balance general proyectado'],
  ['Year-end balances. Properties remain at cost until sold; the model assumes no debt and full liquidation in Year 4.', 'Saldos al cierre del año. Las propiedades permanecen al costo hasta su venta; el modelo supone que no hay deuda y que la liquidación total ocurre en el año 4.'],
  ['USD rounded to whole dollars. Model year-ends fall in September.', 'USD redondeados al dólar. Los años del modelo terminan en septiembre.'],
  ['Model year-end', 'Cierre del año del modelo'],
  ['September ', 'Septiembre '],
  ['Cash', 'Efectivo'],
  ['Real estate at cost', 'Propiedades inmobiliarias al costo'],
  ['Total assets', 'Activos totales'],
  ['Debt and payables', 'Deudas y cuentas por pagar'],
  ['Total equity', 'Patrimonio total'],
  ['Assets equal equity because the model has no debt or payables. The Lola &amp; Ber brand interest has a $0 carrying value. All modeled capital and profit have been distributed by the end of Year 4.', 'Los activos equivalen al patrimonio porque el modelo no contempla deuda ni cuentas por pagar. La participación en la marca Lola &amp; Ber tiene un valor en libros de USD 0. Al cierre del año 4 se habrá distribuido todo el capital y la utilidad modelados.'],
  ['Totals use the workbook’s unrounded balances. Rounded components can differ from totals by $1; negligible floating-point residuals at liquidation display as $0.', 'Los totales usan los saldos sin redondear del archivo. Los componentes redondeados pueden diferir del total en USD 1; los residuos mínimos de punto flotante al liquidar se muestran como USD 0.'],
  ['Period ends:', 'Fechas de cierre:'],
  ['Cash links to Statement of Cash Flows!', 'El efectivo está vinculado al Estado de flujos de efectivo!'],
  ['The source carries the brand interest at zero in Balance Sheet!', 'La fuente registra la participación en la marca en cero en Balance general!'],
  ['Assets, liabilities and equity reconcile within $0.00000001 in the saved values. No source formula or workbook value was changed.', 'Los activos, pasivos y patrimonio cuadran con una diferencia inferior a USD 0,00000001 en los valores guardados. No se modificaron fórmulas ni valores del archivo fuente.'],
  ['Source: Dulcinea Model 07, supplied by Dulcinea.', 'Fuente: Dulcinea Model 07, suministrado por Dulcinea.'],
  ['Projections are subject to the model assumptions. Membership documents govern.', 'Las proyecciones están sujetas a los supuestos del modelo. Prevalecen los documentos de suscripción.'],
  ['Dulcinea One · Financial statements', 'Dulcinea One · Estados financieros'],
  ['The ten acquisition criteria guiding property selection for Dulcinea One.', 'Los diez criterios de adquisición que orientan la selección de propiedades para Dulcinea One.'],
  ['Acquisition criteria', 'Criterios de adquisición'],
  ['Dulcinea One · Property selection', 'Dulcinea One · Selección de propiedades'],
  ['← Back to presentation', '← Volver a la presentación'],
  ['We assess each property against ten acquisition criteria.', 'Evaluamos cada propiedad según diez criterios de adquisición.'],
  ['Ten acquisition tests', 'Diez criterios de adquisición'],
  ['KIT Capital’s acquisition criteria guide property selection for the Dulcinea One fund.', 'Los criterios de adquisición de KIT Capital orientan la selección de propiedades para el fondo Dulcinea One.'],
  ['Ten acquisition criteria', 'Diez criterios de adquisición'],
  ['Location', 'Ubicación'],
  ['El Poblado &amp; El Retiro', 'El Poblado y El Retiro'],
  ['Apartments and penthouses in El Poblado; houses on land in El Retiro.', 'Apartamentos y penthouses en El Poblado; casas en lotes privados en El Retiro.'],
  ['Enjoyment', 'Disfrute'],
  ['Homes we’d want to use', 'Propiedades que quisiéramos disfrutar'],
  ['Places investors would want to spend time in, alongside the investment return.', 'Lugares donde los inversionistas querrían pasar tiempo, además del rendimiento de la inversión.'],
  ['Product', 'Producto'],
  ['Distinctive, larger homes with room to add value.', 'Propiedades amplias y especiales, con potencial para crear valor.'],
  ['Entry price', 'Precio de compra'],
  ['20–30% below improved value', '20–30% por debajo del valor remodelado'],
  ['Compare all-in cost with the home’s renovated comparable value.', 'Comparar el costo total con el valor de propiedades comparables remodeladas.'],
  ['Transformation', 'Transformación'],
  ['About 6 months', 'Alrededor de 6 meses'],
  ['A full remodel, including furniture, fixtures and equipment, to a defined budget.', 'Remodelación integral, incluidos mobiliario, accesorios y equipos, con un presupuesto definido.'],
  ['Due diligence', 'Debida diligencia'],
  ['Technical, legal and title review.', 'Revisión técnica, jurídica y de títulos.'],
  ['Full review before purchase, with a works budget and contingency.', 'Revisión integral antes de comprar, con presupuesto de obra e imprevistos.'],
  ['Operation', 'Operación'],
  ['$300–$1,000 per night', '$300–$1.000 por noche'],
  ['Furnished homes, a 28-night minimum stay and a target cap of $9,500 per 28 nights.', 'Propiedades amobladas, estadía mínima de 28 noches y tarifa objetivo máxima de USD 9.500 por cada 28 noches.'],
  ['Hold &amp; exit', 'Tenencia y salida'],
  ['From purchase to sale, after renovation and a period of rental operation.', 'Desde la compra hasta la venta, después de la remodelación y un periodo de operación en alquiler.'],
  ['Deal size', 'Tamaño de la inversión'],
  ['All-in cost per home.', 'Costo total por propiedad.'],
  ['Minimum return', 'Rendimiento mínimo'],
  ['The deck’s screening hurdle, after carry and gains tax.', 'El mínimo de selección de la presentación, después de la participación de éxito y el impuesto a las ganancias.'],
  ['These are selection targets, subject to property-level underwriting and due diligence. They do not establish that every condition is already satisfied or guarantee a return.', 'Estos son objetivos de selección sujetos al análisis financiero y a la debida diligencia de cada propiedad. No significan que todas las condiciones ya se cumplan ni garantizan un rendimiento.'],
  ['What full due diligence covers', 'Qué incluye una debida diligencia integral'],
  ['Structure, roof, waterproofing, plumbing, electrical systems, humidity, site and soil; permits and licensing; title and liens; HOA rental rules and pending assessments. A works budget with contingency is required before commitment.', 'Estructura, cubierta, impermeabilización, redes hidráulicas y eléctricas, humedad, terreno y suelo; permisos y licencias; títulos y gravámenes; reglas de alquiler de la copropiedad y cuotas extraordinarias pendientes. Antes de comprometerse se requiere un presupuesto de obra con provisión para imprevistos.'],
  ['Targets and the current model', 'Objetivos y modelo vigente'],
  ['The deck’s 15% screening hurdle measures investor-level IRR after carry and gains tax. Model 07 separately targets 20% deal-level IRR after gains tax. These are different return measures. The fund’s projected 15.7% investor IRR is a model output, distinct from either screening target.', 'El mínimo de selección del 15% de la presentación mide la TIR para el inversionista después de la participación de éxito y el impuesto a las ganancias. El Modelo 07, por separado, apunta a una TIR de la operación del 20% después de impuestos a las ganancias. Son medidas distintas. La TIR proyectada de 15,7% para el inversionista es un resultado del modelo, distinto de ambos objetivos de selección.'],
  ['The nightly range and deal-size range are screening targets. Rental rates and budgets are underwritten property by property and may fall outside these ranges.', 'Los rangos de tarifa por noche y tamaño de inversión son objetivos de selección. Las tarifas de alquiler y los presupuestos se analizan propiedad por propiedad y pueden quedar por fuera de estos rangos.'],
  ['The entry discount compares all-in cost with improved comparable value. Each acquisition requires full technical, legal and title review.', 'El descuento de compra compara el costo total con el valor de propiedades comparables remodeladas. Cada adquisición requiere una revisión técnica, legal y de títulos integral.'],
  ['Enjoyment is a property-selection objective. Any investor use rights, allocation or access are governed by the Membership documents.', 'El disfrute es un objetivo de selección de propiedades. Cualquier derecho de uso, asignación o acceso para inversionistas se rige por los documentos de suscripción.'],
  ['Sources', 'Fuentes'],
  ['Selection criteria and model assumptions.', 'Criterios de selección y supuestos del modelo.'],
  ['Dulcinea One · Acquisition criteria', 'Dulcinea One · Criterios de adquisición'],
  ['The whole home', 'La propiedad completa'],
  ['A disciplined budget for each home.', 'Un presupuesto disciplinado para cada propiedad.'],
  ['Hold &amp; exit', 'Tenencia y salida'],
  ['Hold & exit', 'Tenencia y salida'],
  ['Technical, legal and title review.', 'Revisión técnica, jurídica y de títulos.'],
  ['Furnished homes, a 28-night minimum stay and a target cap of $9,500 per 28 nights.', 'Propiedades amobladas, estadía mínima de 28 noches y tarifa objetivo máxima de USD 9.500 por cada 28 noches.'],
  ['From purchase to sale, after renovation and a period of rental operation.', 'Desde la compra hasta la venta, después de la remodelación y un periodo de operación en alquiler.'],
  ['15% investor IRR', 'TIR del 15% para el inversionista'],
  ['Up to 3%', 'Hasta el 3%'],
  ['Pro-rata', 'A prorrata'],
  ['Priority', 'Prioridad'],
  ['20% carry', '20% de participación de éxito'],
  ['Only after all contributed capital is returned. Four-year modeled liquidation.', 'Solo después de devolver todo el capital aportado. Liquidación proyectada a cuatro años.'],
  ['4 years', '4 años'], ['of 6', 'de 6'], ['Return', 'Rendimiento'],
  ['Year-end balances.', 'Saldos al cierre del año.'],
  ['September 2027', 'Septiembre de 2027'], ['September 2028', 'Septiembre de 2028'], ['September 2029', 'Septiembre de 2029'], ['September 2030', 'Septiembre de 2030'],
  ['The whole home', 'La propiedad completa'],
  ['A disciplined budget for each home.', 'Un presupuesto disciplinado para cada propiedad.'],
  ['Hold &amp; exit', 'Tenencia y salida'],
  ['Technical, legal and title review.', 'Revisión técnica, jurídica y de títulos.'],
  ['Furnished homes, a 28-night minimum stay and a target cap of $9,500 per 28 nights.', 'Propiedades amobladas, estadía mínima de 28 noches y tarifa objetivo máxima de USD 9.500 por cada 28 noches.'],
  ['From purchase to sale, after renovation and a period of rental operation.', 'Desde la compra hasta la venta, después de la remodelación y un periodo de operación en alquiler.'],
  ['15% investor IRR', 'TIR del 15% para el inversionista'],
  ['Up to 3%', 'Hasta el 3%'], ['Pro-rata', 'A prorrata'], ['Priority', 'Prioridad'], ['20% carry', '20% de participación de éxito'],
  ['Only after all contributed capital is returned. Four-year modeled liquidation.', 'Solo después de devolver todo el capital aportado. Liquidación proyectada a cuatro años.'],
  ['4 years', '4 años'], ['of 6', 'de 6'], ['Return', 'Rendimiento'],
  ['Year-end balances. Properties remain at cost until sold; the model assumes no debt and full liquidation in Year 4.', 'Saldos al cierre del año. Las propiedades permanecen al costo hasta su venta; el modelo supone que no hay deuda y que la liquidación total ocurre en el año 4.'],
  ['USD rounded to whole dollars. Model year-ends fall in September.', 'USD redondeados al dólar. Los años del modelo terminan en septiembre.'],
  ['Assets equal equity because the model has no debt or payables. The Lola &amp; Ber brand interest has a $0 carrying value. All modeled capital and profit have been distributed by the end of Year 4.', 'Los activos equivalen al patrimonio porque el modelo no contempla deuda ni cuentas por pagar. La participación en la marca Lola &amp; Ber tiene un valor en libros de USD 0. Al cierre del año 4 se habrá distribuido todo el capital y la utilidad modelados.'],
  ['Totals use the workbook’s unrounded balances. Rounded components can differ from totals by $1; negligible floating-point residuals at liquidation display as $0.', 'Los totales usan los saldos sin redondear del archivo. Los componentes redondeados pueden diferir del total en USD 1; los residuos mínimos de punto flotante al liquidar se muestran como USD 0.'],
  ['Cash links to Statement of Cash Flows!C54:F54.', 'El efectivo está vinculado al Estado de flujos de efectivo!C54:F54.'],
  ['Assets, liabilities and equity reconcile within $0.00000001 in the saved values. No source formula or workbook value was changed.', 'Los activos, pasivos y patrimonio cuadran con una diferencia inferior a USD 0,00000001 en los valores guardados. No se modificaron fórmulas ni valores del archivo fuente.'],
  ['Projections are subject to the model assumptions. Membership documents govern.', 'Las proyecciones están sujetas a los supuestos del modelo. Prevalecen los documentos de suscripción.'],
  ['Dulcinea – Investor Presentation 027', 'Dulcinea – Presentación para inversionistas 027'],
  ['“Investment Criteria,”', '“Criterios de inversión,”'],
  ['supplied by Dulcinea. Screening targets and model assumptions are distinguished above.', 'suministrado por Dulcinea. Arriba se distinguen los objetivos de selección y los supuestos del modelo.'],
  ['Dulcinea is a real estate investment firm with a unique platform focused on Medellín, Colombia, presenting its Dulcinea One fund, co-branded by Lola &amp; Ber Hospitality. Content is based on Dulcinea – Investor Presentation 027; figures were checked against Dulcinea Model 07. Projected returns are on called capital, after modeled tax and carry, and are not guaranteed. Membership documents govern.', 'Dulcinea es una firma de inversión inmobiliaria con una plataforma única enfocada en Medellín, Colombia, y presenta su fondo Dulcinea One con la marca compartida Lola &amp; Ber Hospitality. El contenido se basa en Dulcinea – Investor Presentation 027; las cifras se contrastaron con Dulcinea Model 07. Los rendimientos proyectados se calculan sobre el capital aportado, después de impuestos y participación de éxito modelados, y no están garantizados. Prevalecen los documentos de suscripción.'],
  ['Contribution margin is revenue less property cost basis, selling costs and rent-linked fees and taxes. Fixed property costs include predial, insurance, HOA, utilities and maintenance. Fund-level costs include asset management, administration and transaction tax.', 'El margen de contribución corresponde a los ingresos menos el costo base de las propiedades, los gastos de venta y las tarifas e impuestos asociados al alquiler. Los costos fijos de las propiedades incluyen impuesto predial, seguros, administración, servicios públicos y mantenimiento. Los costos del fondo incluyen administración de activos, administración general e impuesto a las transacciones.'],
  ['The model assumes 15% tax on property gains and zero rental income tax after cumulative losses. Totals use unrounded annual values; sums of displayed numbers can differ by $1. Net income is before carry and is not an investor distribution.', 'El modelo supone un impuesto del 15% sobre las ganancias de las propiedades y ningún impuesto sobre los ingresos de alquiler después de pérdidas acumuladas. Los totales usan valores anuales sin redondear; la suma de las cifras mostradas puede diferir en USD 1. La utilidad neta es antes de la participación de éxito y no corresponde a una distribución al inversionista.'],
  ['The opening sequence combines aerial films, a moving city photograph and animated property visualizations. The five property lifestyle illustrations were generated with AI from the supplied property images. Their nine-second videos add slow camera movement; the people are not filmed footage. People and furnishing arrangements are illustrative. Original imagery and the four confirmed floorplan sets remain available from the property pages. Plans preserve source area labels; these can differ from the presentation.', 'La secuencia inicial combina videos aéreos, una fotografía de la ciudad con movimiento y visualizaciones animadas de las propiedades. Las cinco ilustraciones de estilo de vida se generaron con IA a partir de las imágenes suministradas. Sus videos de nueve segundos incorporan movimientos lentos de cámara; las personas no son imágenes filmadas. Las personas y la distribución del mobiliario son ilustrativas. Las imágenes originales y los cuatro juegos de planos confirmados están disponibles en las páginas de cada propiedad. Los planos conservan las áreas indicadas en la fuente, que pueden diferir de las cifras de la presentación.'],
  ['Disfrute is a property-selection objective. Any investor use rights, allocation or access are governed by the Membership documents.', 'El disfrute es un objetivo de selección de propiedades. Cualquier derecho de uso, asignación o acceso para inversionistas se rige por los documentos de suscripción.'],
  ['Sign out', 'Cerrar sesión'],
  ['English (United States)', 'Inglés (Estados Unidos)'],
  ['Español', 'Español'],
  ['United States English', 'Inglés de Estados Unidos'],
  ['Colombian Spanish', 'Español de Colombia'],
  ['Fontanar 201 lifestyle illustration based on supplied property imagery', 'Ilustración de estilo de vida de Fontanar 201 basada en las imágenes suministradas de la propiedad'],
  ['Casa Montana lifestyle visualization with fictional adults', 'Visualización de estilo de vida de Casa Montana con adultos ficticios'],
  ['Photorealistic lifestyle visualization of San Lucas 101 with fictional adults', 'Visualización de estilo de vida fotorrealista de San Lucas 101 con adultos ficticios'],
  ['Photorealistic lifestyle visualization of Aires de Campestre with fictional adults', 'Visualización de estilo de vida fotorrealista de Aires de Campestre con adultos ficticios'],
  ['Photorealistic lifestyle visualization of Fontanar 201 with fictional adults', 'Visualización de estilo de vida fotorrealista de Fontanar 201 con adultos ficticios'],
  ['Photorealistic lifestyle visualization of Casa Monte Sereno with fictional adults', 'Visualización de estilo de vida fotorrealista de Casa Monte Sereno con adultos ficticios'],
  ['Photorealistic lifestyle visualization of Casa Montana with fictional adults', 'Visualización de estilo de vida fotorrealista de Casa Montana con adultos ficticios'],
  ['San Lucas 101 · Lifestyle visualization', 'San Lucas 101 · Visualización de estilo de vida'],
  ['Aires de Campestre · Lifestyle visualization', 'Aires de Campestre · Visualización de estilo de vida'],
  ['Fontanar 201 · Lifestyle visualization', 'Fontanar 201 · Visualización de estilo de vida'],
  ['Casa Monte Sereno · Lifestyle visualization', 'Casa Monte Sereno · Visualización de estilo de vida'],
  ['Casa Montana · Lifestyle visualization', 'Casa Montana · Visualización de estilo de vida'],
  ['San Lucas 101 AI lifestyle visualization with fictional adults', 'Visualización de estilo de vida de San Lucas 101 generada con IA, con adultos ficticios'],
  ['Aires de Campestre AI lifestyle visualization with fictional adults', 'Visualización de estilo de vida de Aires de Campestre generada con IA, con adultos ficticios'],
  ['Fontanar 201 AI lifestyle visualization with fictional adults', 'Visualización de estilo de vida de Fontanar 201 generada con IA, con adultos ficticios'],
  ['Casa Monte Sereno AI lifestyle visualization with fictional adults', 'Visualización de estilo de vida de Casa Monte Sereno generada con IA, con adultos ficticios'],
  ['Casa Montana AI lifestyle visualization with fictional adults', 'Visualización de estilo de vida de Casa Montana generada con IA, con adultos ficticios'],
  ['Dulcinea Model 07.xlsx, Income Statement!C:F, rows 7, 18, 29, 109–111, 139, 144, 147, 152 and 154.', 'Dulcinea Model 07.xlsx, Income Statement!C:F, filas 7, 18, 29, 109–111, 139, 144, 147, 152 y 154.'],
  ['Dulcinea Model 07.xlsx, Balance Sheet!C7:F10, C13:F14 and C20:F22.', 'Dulcinea Model 07.xlsx, Balance Sheet!C7:F10, C13:F14 y C20:F22.'],
  ['Dulcinea Model 07.xlsx', 'Dulcinea Model 07.xlsx'],
  ['Aerial view over Medellín’s green city towers', 'Vista aérea de los edificios de Medellín entre montañas y zonas verdes'],
  ['San Lucas 101 - Floor 1; complete supplied drawing', 'San Lucas 101 - Planta 1; plano completo suministrado'],
  ['San Lucas 101 - Floor 2; complete supplied drawing', 'San Lucas 101 - Planta 2; plano completo suministrado'],
  ['Aires del Campestre - Floor 1; complete supplied drawing', 'Aires del Campestre - Planta 1; plano completo suministrado'],
  ['Aires del Campestre - Floor 2; complete supplied drawing', 'Aires del Campestre - Planta 2; plano completo suministrado'],
  ['Fontanar - Floor 1; complete supplied drawing', 'Fontanar - Planta 1; plano completo suministrado'],
  ['Fontanar - Floor 2; complete supplied drawing', 'Fontanar - Planta 2; plano completo suministrado'],
  ['Monte Sereno - Site plan; complete supplied drawing', 'Monte Sereno - Plano del lote; plano completo suministrado'],
  ['Monte Sereno - Floor 1; complete supplied drawing', 'Monte Sereno - Planta 1; plano completo suministrado'],
  ['Monte Sereno - Roof plan; complete supplied drawing', 'Monte Sereno - Plano de cubierta; plano completo suministrado'],
  ['Area labels are as supplied.', 'Las etiquetas de área son las suministradas.'],
  ['Original imagery supplied in the investor presentation', 'Imágenes originales suministradas en la presentación para inversionistas'],
  ['No brand fee in the proposed model.', 'El modelo propuesto no contempla un cobro por uso de marca.'],
  ['People and furnishing arrangements are illustrative.', 'Las personas y la distribución del mobiliario son ilustrativas.'],
  ['A signed property is not presented as a completed closing.', 'Una propiedad firmada no se presenta como una compra ya cerrada.'],
  ['availability', 'disponibilidad'],
  ['Language', 'Idioma'],
  ['Fontanar 201 · AI lifestyle visualization', 'Fontanar 201 · Visualización de estilo de vida generada con IA'],
  ['San Lucas 101 · AI lifestyle visualization', 'San Lucas 101 · Visualización de estilo de vida generada con IA'],
  ['Casa Montana · AI lifestyle visualization', 'Casa Montana · Visualización de estilo de vida generada con IA'],
  ['San Lucas - Floor 1', 'San Lucas - Planta 1'], ['San Lucas - Floor 2', 'San Lucas - Planta 2'],
  ['Aires del Campestre - Floor 1', 'Aires del Campestre - Planta 1'], ['Aires del Campestre - Floor 2', 'Aires del Campestre - Planta 2'],
  ['Fontanar - Floor 1', 'Fontanar - Planta 1'], ['Fontanar - Floor 2', 'Fontanar - Planta 2'],
  ['Monte Sereno - Site plan', 'Monte Sereno - Plano del lote'], ['Monte Sereno - Floor 1', 'Monte Sereno - Planta 1'], ['Monte Sereno - Roof plan', 'Monte Sereno - Plano de cubierta'],
  ['24–36 months', '24–36 meses'],
  ['<small>of 6</small>', '<small>de 6</small>'],
  [' and ', ' y '],
  ['Night-road footage dissolving into animated nightlife photographs', 'Video de calles nocturnas que da paso a fotografías animadas de la vida nocturna'],
  ['Photorealistic lifestyle visualization', 'Visualización fotorrealista de estilo de vida'],
  ['AI lifestyle visualization', 'Visualización de estilo de vida generada con IA'],
  ['original supplied property imagery', 'imágenes originales suministradas de la propiedad'],
  ['Source page ', 'Página de origen '],
  ['Fontanar 201 · Supplied architectural plan', 'Fontanar 201 · Plano arquitectónico suministrado'],
  ['KIT Capital and Lola &amp; Ber Hospitality', 'KIT Capital y Lola &amp; Ber Hospitality'],
  ['30 years operating and restructuring businesses, including HP, Dell and RealNetworks. Led M&amp;A on $1.5B of transactions.', 'Treinta años de experiencia operando y reestructurando empresas, incluidas HP, Dell y RealNetworks. Lideró fusiones y adquisiciones en transacciones por USD 1.500 millones.'],
  ['Supplied architectural floorplan for Fontanar, first floor', 'Plano arquitectónico suministrado de Fontanar, primer piso'],
  [', Income Statement!C:F, rows 7, 18, 29, 109–111, 139, 144, 147, 152 and 154. Model periods: C5:F5. Property-gains tax assumption: Input!C26; rental tax calculation: Income Statement!C150:F150.', ', Income Statement!C:F, filas 7, 18, 29, 109–111, 139, 144, 147, 152 y 154. Periodos del modelo: C5:F5. Supuesto de impuesto sobre ganancias de propiedades: Input!C26; cálculo del impuesto sobre alquileres: Income Statement!C150:F150.'],
  [', Balance Sheet!C7:F10, C13:F14 and C20:F22. Period ends: C5:F5. Cash links to Statement of Cash Flows!C54:F54. The source carries the brand interest at zero in Balance Sheet!C9:F9.', ', Balance Sheet!C7:F10, C13:F14 y C20:F22. Fechas de cierre: C5:F5. El efectivo está vinculado al Estado de flujos de efectivo!C54:F54. La fuente registra la participación en la marca en cero en Balance Sheet!C9:F9.'],
  [', “Investment Criteria,” and ', ', “Criterios de inversión,” y '],
  ['M&amp;A', 'fusiones y adquisiciones'],
  ['Hold and exit', 'Tenencia y salida'],
  ['Explore the five homes', 'Explora las cinco propiedades'],
  ['Dulcinea One investor presentation', 'Presentación para inversionistas de Dulcinea One'],
  ['30 percent of the 7 million dollar fund raise is committed', 'El 30% de la meta de capital de USD 7 millones ya está comprometido'],
  ['Dulcinea One investor presentation', 'Presentación para inversionistas de Dulcinea One'],
  ['Explore the five homes', 'Explora las cinco propiedades'],
  ['Property image; zoom to inspect details', 'Imagen de la propiedad; amplía para ver los detalles'],
  ['30 percent of the 7 million dollar fund raise is committed', 'El 30% de la meta de capital de USD 7 millones ya está comprometido'],
  ['30 percent de the 7 million dollar fund raise is committed', 'El 30% de la meta de capital de USD 7 millones ya está comprometido'],
  ['INVESTOR PRESENTATION', 'PRESENTACIÓN PARA INVERSIONISTAS'],
  ['>Top</span>', '>Inicio</span>'],
  ['of 6', 'de 6'],
  ['Hold and exit', 'Tenencia y salida'],
  ['Hold and exit', 'Tenencia y salida'],
  ['Aerial view over Medellín’s green city towers', 'Vista aérea de los edificios de Medellín entre montañas y zonas verdes'],
  ['Projected income statement in USD; scroll horizontally for all years', 'Estado de resultados proyectado en USD; desplázate horizontalmente para ver todos los años'],
  ['Projected balance sheet in USD; scroll horizontally for all years', 'Balance general proyectado en USD; desplázate horizontalmente para ver todos los años'],
  ['Dulcinea Model 07.xlsx, Income Statement!C:F, rows 7, 18, 29, 109–111, 139, 144, 147, 152 and 154. Model periods: C5:F5. Property-gains tax assumption: Input!C26; rental tax calculation: Income Statement!C150:F150.', 'Dulcinea Model 07.xlsx, Income Statement!C:F, filas 7, 18, 29, 109–111, 139, 144, 147, 152 y 154. Periodos del modelo: C5:F5. Supuesto de impuesto sobre ganancias de propiedades: Input!C26; cálculo del impuesto sobre alquileres: Income Statement!C150:F150.'],
  ['Dulcinea Model 07.xlsx, Balance Sheet!C7:F10, C13:F14 and C20:F22. Period ends: C5:F5. Cash links to Statement of Cash Flows!C54:F54. The source carries the brand interest at zero in Balance Sheet!C9:F9.', 'Dulcinea Model 07.xlsx, Balance Sheet!C7:F10, C13:F14 y C20:F22. Fechas de cierre: C5:F5. El efectivo está vinculado al Estado de flujos de efectivo!C54:F54. La fuente registra la participación en la marca en cero en Balance Sheet!C9:F9.'],
  ['Dulcinea Model 07.xlsx, Income Statement!C:F, rows 7, 18, 29, 109–111, 139, 144, 147, 152 and 154.', 'Dulcinea Model 07.xlsx, Income Statement!C:F, filas 7, 18, 29, 109–111, 139, 144, 147, 152 y 154.'],
];

export function toColombianSpanish(input) {
  const { value, protect, restore } = preserveFinancialIdentifiers(input);
  let output = value;
  for (const [english, spanish] of [...translations].sort(([left], [right]) => right.length - left.length)) {
    output = output.replaceAll(protect(english), protect(spanish));
  }
  return restore(output);
}
